// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMA4E_wqRlGDiuzTszm7SRziH-bnGHJiM',
    appId: '1:890884140730:web:75a279ba21f41265f29c83',
    messagingSenderId: '890884140730',
    projectId: 'location-finder-app-28e66',
    authDomain: 'location-finder-app-28e66.firebaseapp.com',
    storageBucket: 'location-finder-app-28e66.appspot.com',
    measurementId: 'G-7PLR9DMMNT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFvlGUsDd3ac9GsaYap0XpOn3Q1TcMfjw',
    appId: '1:890884140730:android:179084789a1577a5f29c83',
    messagingSenderId: '890884140730',
    projectId: 'location-finder-app-28e66',
    storageBucket: 'location-finder-app-28e66.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwZIS30jbrAshKjrBRNA193z9yFAg1-58',
    appId: '1:890884140730:ios:34c716740bf23f72f29c83',
    messagingSenderId: '890884140730',
    projectId: 'location-finder-app-28e66',
    storageBucket: 'location-finder-app-28e66.appspot.com',
    iosBundleId: 'com.example.geoLocationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwZIS30jbrAshKjrBRNA193z9yFAg1-58',
    appId: '1:890884140730:ios:71bb45f058dbc780f29c83',
    messagingSenderId: '890884140730',
    projectId: 'location-finder-app-28e66',
    storageBucket: 'location-finder-app-28e66.appspot.com',
    iosBundleId: 'com.example.geoLocationApp.RunnerTests',
  );
}
